name: PatternClass
<<<<<<< HEAD
version: 2.4
date: 11/08/2017
=======
version: 2.3
date: 05/07/2017
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3
description: |
    A permutation pattern class package

authors:
    - name: Ruth Hoffmann
<<<<<<< HEAD
      url: https://rh347.host.cs.st-andrews.ac.uk/
=======
      url: https://www.hoffmannandco.com
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3
    - name: Steve Linton
      url: http://sal.host.cs.st-andrews.ac.uk/
    - name: Michael Albert
      url: http://www.cs.otago.ac.nz/staff/michael.html

maintainers:
    - name: Ruth Hoffmann
<<<<<<< HEAD
      url: https://rh347.host.cs.st-andrews.ac.uk/
=======
      url: https://www.hoffmannandco.com
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3

GAP: ">= 4.8"

needed-pkgs:
    - name: "Automata"
      version: ">=1.13"
      url: "http://www.fc.up.pt/cmup/mdelgado/automata"
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://RuthHoffmann.github.io/PatternClass/
readme: README.md
packageinfo: https://RuthHoffmann.github.io/PatternClass/PackageInfo.g

downloads:
    - name: .tar.gz
<<<<<<< HEAD
      url: https://github.com/RuthHoffmann/PatternClass/releases/download/v2.4/PatternClass-2.4.tar.gz
=======
      url: https://github.com/RuthHoffmann/PatternClass/releases/download/v2.3/PatternClass-2.3.tar.gz
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3

abstract: |
    

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
